### ISSUE TITLE
Check on automated updating

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portal-forecast-web#38]
Based on not seeing updates on the website I checked the server today and the data hadn't been updated since June. I manually ran `fill_dir()` which has updated everything, but we need to figure out why the automated updates hadn't worked.

`cron.log` did indicate that things had been run in the last week, but the cronjob itself is under @henrykironde's account so I couldn't look into the details of what is going on. @henrykironde - I'm going to leave this one to you to look into. Let me know if I can be of any help.

The one thing that didn't update (still has write dates from June) is the `data/*_interp.csv` files. @juniperlsimonis - is there something we need to do to trigger those to rebuild once the most recent data is downloaded?

**Comment by ethanwhite** [comment]
Via Slack:

>the interp csvs should not be needed anymore, as we included the interpolation in another part of the workflow, so the only csvs getting saved should be un-interpolated

I have deleted the remaining `*_interp.csv` files.

**Comment by henrykironde** [comment]
Seems to be working as required at the moment.
