### ISSUE TITLE
Add plausible tracking

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portal-forecast-web#55]
We switching to [Plausible](https://plausible.io/) for more ethical usage tracking. We need to add the following code to the head tag on the website:

```
<script defer data-domain="portal.naturecast.org" src="https://plausible.io/js/script.js"></script>
```

We used to do something like this with Google Analytics, but it's not clear to me if we still do.

**Comment by ethanwhite** [comment]
That is the only line that needs to be added, but it needs to be in the head tag of every page on the shiny site. This is complicated by the fact that (I think) the site is now being built by https://github.com/weecology/portalcasting/ not by the code in the `app` directory.

@henrykironde or @gmyenni do either of you remember the details of how the website is building at the moment and whether it's coming from `portalcasting` or from the `app` directory here?

**Comment by henrykironde** [comment]
Thanks @ethanwhite  and @Girishbari for the comments on this issue.
